### ISSUE TITLE
cant access the site both the kiosk and cloud

### ISSUE THREAD

**Issue by acmiras** [vasavah/vci-kanaka_auntie-annes-testing-phase#54]
![image](https://user-images.githubusercontent.com/60170851/92188863-50694900-ee90-11ea-9682-4c2d43e5bdbf.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92188946-8ad2e600-ee90-11ea-9d34-da741c1b0a39.png)

**Comment by VCI-Jojo** [comment]
@acmiras Please install AnyDesk to your workstation so I can check your settings and troubleshoot remotely. Thanks

https://anydesk.com/en/downloads

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92192612-f0c36b80-ee98-11ea-8905-56fde49f7f56.png)

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92192631-00db4b00-ee99-11ea-8f10-27cb68841eca.png)

**Comment by VCI-Jojo** [comment]
@acmiras As per our phone call earlier, we've fixed the loading issue reported, please confirm on your end. Thank you.

**Comment by acmiras** [comment]
![image](https://user-images.githubusercontent.com/60170851/92203679-54a75d80-eeb4-11ea-9252-d5efff6a5cbf.png)
 STILL CANT ACCESS KIOSK

**Comment by VCI-Jojo** [comment]
@acmiras We've applied a patch for the Kiosk yesterday, kindly validate if you can access already. Thank you.
